######################################
# Configuration for ttyrecall daemon #
######################################

root = "/var/lib/ttyrecall"
# Compression
# - none        : no compression
# - zstd        : zstd with default compression level
# - zstd:$level : zstd with custom compression level
compress = "zstd"

# Mode
# - blocklist: Record all pty sessions by default, but sessions from listed users/uids won't be recorded
# - allowlist: Only record the pty sessions from listed users/uids
mode = "blocklist"
# User names
users = []
# UIDs
uids = [
    0, # The root user's session is not interesting most of the time
]
# Ignore pty sessions opened by process with following comms
excluded_comms = [
    "sudo", # While sudo opens a new pty but we also have the contents available in parent pty.
    "asciinema", # Usually it's not helpful to record it again when it is already being recorded by asciinema.
]

# Soft budget for every recording file. The recording will stop after it overruns the budget.
# Unit: bytes
# A special value of zero will disable the soft budget.
soft_budget = 52428800
